### ISSUE TITLE
Document working with gulp

### ISSUE THREAD

**Issue by PFight** [nfroidure/StreamQueue#10]
To work with gulp we should add { objectMode: true } as the first parameter (due to gulp generates old streams). Like this:

    return streamqueue({ objectMode: true }, build, inject);

Can you add this info to pakage description? I think many peoples gets error 'TypeError: Invalid non-string/buffer chunk' when trying to  use streamqueue in gulp environment.

**Comment by nfroidure** [comment]
There is something about that in the doc https://github.com/nfroidure/StreamQueue#streamqueueobjoptions-stream1-stream2--streamn

Feel free to PR if you find that the documentation lacks a custom Gulp warning, i'll be happy to merge it.
