### ISSUE TITLE
readable-stream dependency change is a breaking change (use semantic versioning)

### ISSUE THREAD

**Issue by moustafab** [nfroidure/streamqueue#11]
## Issue

I'm a gentledev i:
- [x] fully read the README recently
- [x] searched for existing issues
- [x] checked i'm up to date with the latest version of the project

### 
### Feature description
Use semantic versioning, and up a major version when an un-abstracted dependency like readable-stream is bumped a major version.
### Use cases

Because readable-stream version was bumped in the latest release, but the version of this package was only patched, it was quite difficult to figure out why gulp scripts for some of our projects using your package stopped working. Readable streams breaking changes constituted major breaking changes to this package as well.

**Comment by nfroidure** [comment]
Given this package coverage and the fact tests passed, I never thought it would break anything. What happened?

**Comment by moustafab** [comment]
looks like readable-stream doesn't work with gulp properly, because using gulp 3.9.1, and the latest version of streamqueue the stream events for 'end' and others were not firing.

**Comment by chriszrc** [comment]
@moustafab thank you so much, I haven't used gulp in years, but I had to make a change to a project from 2014, and had no freaking idea why it was silently failing. But it stopped at streamqueue, which led me here. Thank You!!!
